"""empty message

Revision ID: 3fc552785dcf
Revises: f8e79d2b43a8
Create Date: 2026-07-13 15:35:25.950585

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3fc552785dcf'
down_revision = 'f8e79d2b43a8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('escrow_orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reference', sa.String(length=100), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('marketer_id', sa.Integer(), nullable=True),
    sa.Column('total_amount', sa.Float(), nullable=False),
    sa.Column('commission_amount', sa.Float(), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=True),
    sa.Column('gateway', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('customer_name', sa.String(length=150), nullable=True),
    sa.Column('customer_email', sa.String(length=150), nullable=True),
    sa.Column('customer_phone', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('seller_fulfilled_at', sa.DateTime(), nullable=True),
    sa.Column('buyer_confirmed_at', sa.DateTime(), nullable=True),
    sa.Column('released_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['marketer_id'], ['marketers.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('reference')
    )
    with op.batch_alter_table('conversions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reference', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('gateway', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('customer_email', sa.String(length=150), nullable=True))
        batch_op.add_column(sa.Column('released_at', sa.DateTime(), nullable=True))
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=50),
               existing_nullable=True)
        batch_op.create_unique_constraint(None, ['reference'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('conversions', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('status',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)
        batch_op.drop_column('released_at')
        batch_op.drop_column('customer_email')
        batch_op.drop_column('gateway')
        batch_op.drop_column('reference')

    op.drop_table('escrow_orders')
    # ### end Alembic commands ###
