"""empty message

Revision ID: f8e79d2b43a8
Revises: 08b0e3d72441
Create Date: 2026-07-12 18:12:47.260482

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f8e79d2b43a8'
down_revision = '08b0e3d72441'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('marketers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cooplead_user_id', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    with op.batch_alter_table('marketers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_marketers_cooplead_user_id'), ['cooplead_user_id'], unique=True)

    op.create_table('conversions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=True),
    sa.Column('marketer_id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('sale_amount', sa.Float(), nullable=False),
    sa.Column('commission_earned', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['marketer_id'], ['marketers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuid')
    )
    op.drop_table('tracking_rules')
    with op.batch_alter_table('tenants', schema=None) as batch_op:
        batch_op.drop_column('cooplead_enabled')
        batch_op.drop_column('reward_model')
        batch_op.drop_column('commission_rate')
        batch_op.drop_column('cooplead_campaign_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tenants', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cooplead_campaign_id', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('commission_rate', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('reward_model', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('cooplead_enabled', sa.BOOLEAN(), autoincrement=False, nullable=True))

    op.create_table('tracking_rules',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('event_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('marks_awarded', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('selector', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='tracking_rules_pkey')
    )
    op.drop_table('conversions')
    with op.batch_alter_table('marketers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_marketers_cooplead_user_id'))

    op.drop_table('marketers')
    # ### end Alembic commands ###
